// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mc2.CrudTest.AcceptanceTests.UI.EndToEndTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateReadEditDeleteCustomerFeature : object, Xunit.IClassFixture<CreateReadEditDeleteCustomerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CustomerManager.feature"
#line hidden
        
        public CreateReadEditDeleteCustomerFeature(CreateReadEditDeleteCustomerFeature.FixtureData fixtureData, Mc2_CrudTest_AcceptanceTests_UI_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EndToEndTests/Features", "Create Read Edit Delete Customer", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
    #line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Code",
                        "Description"});
            table1.AddRow(new string[] {
                        "101",
                        "Invalid Mobile Number"});
            table1.AddRow(new string[] {
                        "102",
                        "Invalid Email address"});
            table1.AddRow(new string[] {
                        "103",
                        "Invalid Bank Account Number"});
            table1.AddRow(new string[] {
                        "201",
                        "Duplicate customer by First-name, Last-name, Date-of-Birth"});
            table1.AddRow(new string[] {
                        "202",
                        "Duplicate customer by Email address"});
#line 4
        testRunner.Given("system error codes are following", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create Read Edit Delete Customer in blazor ui", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Read Edit Delete Customer")]
        [Xunit.TraitAttribute("Description", "Create Read Edit Delete Customer in blazor ui")]
        public void CreateReadEditDeleteCustomerInBlazorUi()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Read Edit Delete Customer in blazor ui", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
    this.FeatureBackground();
#line hidden
#line 14
        testRunner.Given("Browser at customers page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table2.AddRow(new string[] {
                            "John",
                            "Doe",
                            "john@doe.com",
                            "+989121234567",
                            "01-JAN-2000",
                            "IR000000000000001"});
#line 15
        testRunner.When("user fills CreateCustomer form by following data and clicks Create button", ((string)(null)), table2, "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table3.AddRow(new string[] {
                            "John",
                            "Doe",
                            "john@doe.com",
                            "+989121234567",
                            "01-JAN-2000",
                            "IR000000000000001"});
#line 18
        testRunner.Then("user can look at customers list and find \"1\" records by below properties", ((string)(null)), table3, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table4.AddRow(new string[] {
                            "John",
                            "Doe",
                            "other@doe.com",
                            "+989121234567",
                            "01-JAN-2000",
                            "IR000000000000001"});
#line 21
        testRunner.When("user fills CreateCustomer form by following data and clicks Create button", ((string)(null)), table4, "When ");
#line hidden
#line 24
        testRunner.Then("user must get error message of code \"201\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
        testRunner.When("user clicks edit button on customers list for customer by email of \"john@doe.com\"" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table5.AddRow(new string[] {
                            "Jane",
                            "William",
                            "jane@william.com",
                            "+3161234567",
                            "01-FEB-2010",
                            "IR000000000000002"});
#line 26
        testRunner.And("user fills UpdateCustomer form by following data and clicks Update button", ((string)(null)), table5, "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table6.AddRow(new string[] {
                            "John",
                            "Doe",
                            "john@doe.com",
                            "+989121234567",
                            "01-JAN-2000",
                            "IR000000000000001"});
#line 29
        testRunner.Then("user can look at customers list and find \"0\" records by below properties", ((string)(null)), table6, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table7.AddRow(new string[] {
                            "Jane",
                            "William",
                            "jane@william.com",
                            "+3161234567",
                            "01-FEB-2010",
                            "IR000000000000002"});
#line 32
        testRunner.And("user can look at customers list and find \"1\" records by below properties", ((string)(null)), table7, "And ");
#line hidden
#line 35
        testRunner.When("user clicks delete button on customers list for customer by email of \"jane@willia" +
                        "m.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
        testRunner.Then("user can get all records and get \"0\" records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateReadEditDeleteCustomerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateReadEditDeleteCustomerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
