version: '3.4'

volumes:
  crud_test_data:

services:
  mc2.crudtest.blazor:
    image: ${DOCKER_REGISTRY-}mc2crudtestblazor
    build:
      context: .
      dockerfile: Mc2.CrudTest.blazor/Dockerfile
    ports:
      - 80:80
    depends_on:
      - mc2.crudtest.api

  mc2.crudtest.api:
    image: ${DOCKER_REGISTRY-}mc2crudtestapi
    build:
      context: .
      dockerfile: Mc2.CrudTest.Api/Dockerfile
    depends_on:
      - crud-test-sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  crud-test-sql-server:
    container_name: crud-test-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - crud_test_data:/var/opt/mssql
    environment:
      # Since this is a test project, it's okay to put passwords in source control
      SA_PASSWORD: "!@QW34ertyui"
      ACCEPT_EULA: "Y"
